#!/bin/sh
# File generated by ocamlbuild

cd /home/dchar/M1_STIC_INFO/s8/INFO-OCAML/LispLike

rm -f ast.annot
# Also clean the script itself
rm -f /home/dchar/M1_STIC_INFO/s8/INFO-OCAML/LispLike/_build/sanitize.sh
